### PR TITLE
melon's dress

### PR DESCRIPTION
**Pull request by hankai17**
My dress. I'm melon.

### CODE REVIEW

**Comment by a-wing** [comment]
So cute (

**Comment by hankai17** [comment]
@a-wing :)

**Comment by TotooriaHyperion** [comment]
These photos are yurisa_chans'.
You are the famous Korean female model yurisa_chan?
I thought this repo only accepts MTF/CD photo.
@AkechiSatori

**Comment by zh99998** [comment]
female is also acceptable. @TotooriaHyperion

**Comment by hankai17** [comment]
ping @TotooriaHyperion 
This just "opensource".

**Comment by zh99998** [comment]
are you yurisa_chan? @hankai17

**Comment by hankai17** [comment]
ping @zh99998 
absolutely funs :)

**Comment by zh99998** [comment]
so the person in photo is not you? @hankai17

**Comment by HerringtonDarkholme** [comment]
Imposter should be no-go here.

**Pull request merged**
