### PR TITLE
Add english version to README

### PR DESCRIPTION
**Pull request by Songkeys**
Since it's on trending now...

### CODE REVIEW

**Comment by Misaka-0x447f** [comment]
Thanks since WHY ON EARTH it could be trending...

**Comment by huxiaoyun** [comment]
so many cute boys ...

**Comment by Misaka-0x447f** [comment]
@huxiaoyun Most of them want's to be called "girls"

**Comment by ycwei982** [comment]
@Misaka-0x447f 

That pushed too hard.

We need to clarify that crossdressing is different from gender dysphoria. 

If someone like crossdressing, it doesn't mean that guy really wants to be called as female. Maybe it's just a hobby, or not.

**Pull request merged**
