### PR TITLE
尽可能忍住你的好奇心除非忍不住

### PR DESCRIPTION
**Pull request by LuhangRui**
令人头皮发麻发麻的操作啊（逃），会接受这个PR么？啊哈哈哈

### CODE REVIEW

**Comment by zumoA** [comment]
太草

**Comment by rekols** [comment]
令人窒息的操作

**Comment by Mouse0w0** [comment]
Don‘t merge this pull request! Oh my f**king god!

**Comment by rekols** [comment]
@Mouse0w0 Are you ok ???

**Comment by Mouse0w0** [comment]
@rekols I'm really feeling bad.

**Comment by rekols** [comment]
@Mouse0w0 Super high, felling as if my life was reached a climax....

**Comment by rekols** [comment]
@ruiluhang 删了干啥啊，说不定还能合进去呢

**Comment by Mouse0w0** [comment]
@rekols 👍

**Comment by rekols** [comment]
https://github.com/komeiji-satori/Dress/pull/124/commits/72705f187838aac6026b233a4a9cca27891a074c  

@Mouse0w0 look at here.

**Comment by LuhangRui** [comment]
> @ruiluhang 删了干啥啊，说不定还能合进去呢

没删，就是对README做了修改，增加高能预警，毕竟另一个兄台说他看了感觉非常难受

**Comment by rekols** [comment]
> > @ruiluhang 删了干啥啊，说不定还能合进去呢
> 
> 没删，就是对README做了修改，增加高能预警，毕竟另一个兄台说他看了感觉非常难受

Please speak english, thx.

**Comment by rekols** [comment]
@Mouse0w0 Can you submit a similar pull request?

**Comment by Mouse0w0** [comment]
@rekols NO! If I want to submit a pull request, I will try my best. :)

**Comment by rekols** [comment]
@Mouse0w0 Are you beautiful?

**Comment by Mouse0w0** [comment]
@rekols No, And you? Why not submit a pull request?

**Comment by zh99998** [comment]
Nope

**Comment by rekols** [comment]
@zh99998 why close this pull request ?

**Comment by rekols** [comment]
@Mouse0w0 because i am ugly.

**Pull request closed without merging**
